Sys.setlocale("LC_TIME", "en_US.UTF-8")
consumption<-read.csv("household_power_consumption.txt",sep=";",dec=".",na.strings=c("?"))
consumption$Time<-strptime(paste(consumption$Date,consumption$Time),"%d/%m/%Y %H:%M:%S")
consumption$Date<-as.Date(consumption$Date,"%d/%m/%Y")
consumptionData<-subset(consumption,Date=="2007-02-01" | Date=="2007-02-02")
png("plot4.png",480,480,bg="transparent")
attach(consumptionData)
par(mfrow=c(2,2))
plot(Time,Global_active_power,ylab="Global Active Power",xlab="",type="l")
plot(Time,Voltage,ylab="Voltage",xlab="datetime",type="l")
plot(Time,Sub_metering_1,ylab="Energy sub metering",xlab="",type="l")
lines(Time,Sub_metering_2,col="red")
lines(Time,Sub_metering_3,col="blue")
legend("topright", lty=1, col =c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n")
plot(Time,Global_reactive_power,xlab="datetime",type="l")
dev.off()
