Sys.setlocale("LC_TIME", "en_US.UTF-8")
consumption<-read.csv("household_power_consumption.txt",sep=";",dec=".",na.strings=c("?"))
consumption$Time<-strptime(paste(consumption$Date,consumption$Time),"%d/%m/%Y %H:%M:%S")
consumption$Date<-as.Date(consumption$Date,"%d/%m/%Y")
consumptionData<-subset(consumption,Date=="2007-02-01" | Date=="2007-02-02")
png("plot2.png",480,480,bg="transparent")
attach(consumptionData)
plot(Time,Global_active_power,ylab="Global Active Power (kilowatts)",xlab="",type="l")
dev.off()
